version: '3.1'
services:
  dbpostgresql:
    image: "postgres:12"
    container_name: dbpostgresql

    ports:
      - "5436:5432"
    volumes: 
      - /.app
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: demo
    image: demo

    build: demo/
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  quartz:
    container_name: spring-quartz
    image: spring-quartz

    build: spring-quartz/
    ports:
      - "8099:8099"
    depends_on:
      - dbpostgresql
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - "9093"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper


  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
